services:
  # Backend API for incident safety logs
  api:
    build:
      context: ./api
      dockerfile: Dockerfile 
    container_name: backend_api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: always 

  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: sparkle_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d 
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env

  # Redis cache
  redis:
    image: redis:latest
    container_name: sparkle_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:
